"""Agregar modelo OrdenServicio

Revision ID: 3e86343f5de8
Revises: 1547756a3caf
Create Date: 2024-11-26 07:10:29.715052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e86343f5de8'
down_revision = '1547756a3caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proforma')
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    op.create_table('proforma',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vehiculo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('costo_estimado', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('kilometraje', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('marca', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('modelo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name='proforma_cliente_id_fkey'),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], name='proforma_vehiculo_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='proforma_pkey')
    )
    # ### end Alembic commands ###
