"""Agregar modelos Cliente y Vehículo

Revision ID: 7a5b852ef8c2
Revises: 
Create Date: 2024-11-25 23:29:50.324044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5b852ef8c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anio', sa.String(length=4), nullable=False))
        batch_op.drop_column('ano_vehiculo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ano_vehiculo', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
        batch_op.drop_column('anio')

    # ### end Alembic commands ###
